project:
  type: book

book:
  title: "General Computer Science"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - reading.qmd
  page-navigation: true

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


toc-depth: 4
number-depth: 1
